Don't call job_runner.stop_job on jobs in new state
These aren't submitted yet, no point in doing that.
Fixes
https://sentry.galaxyproject.org/share/issue/ea06518238f1409eb22a8f502f9db557/:
```
AssertionError: External job id is None
  File "galaxy/jobs/runners/drmaa.py", line 375, in stop_job
    assert ext_id not in (None, "None"), "External job id is None"
```